name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode 15.3
      run: |
        sudo xcode-select --switch /Applications/Xcode_15.3.app

    - name: SPM Cache
      uses: actions/cache@v3.3.2
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Build
      run: swift build -v

    - name: Run tests
      run: make test
